// This file was generated by gen_melodies.py
#pragma once
#include "core/sound.hpp"
namespace melodies {
    constexpr sound::Note cmajor[] = {
        {sound::NoteFrequency::NOTE_C4, 200},
        {sound::NoteFrequency::NOTE_D4, 200},
        {sound::NoteFrequency::NOTE_E4, 200},
        {sound::NoteFrequency::NOTE_F4, 200},
        {sound::NoteFrequency::NOTE_G4, 200},
        {sound::NoteFrequency::NOTE_A4, 200},
        {sound::NoteFrequency::NOTE_B4, 200},
        {sound::NoteFrequency::NOTE_C5, 200},
        {sound::NoteFrequency::NOTE_B4, 200},
        {sound::NoteFrequency::NOTE_A4, 200},
        {sound::NoteFrequency::NOTE_G4, 200},
        {sound::NoteFrequency::NOTE_F4, 200},
        {sound::NoteFrequency::NOTE_E4, 200},
        {sound::NoteFrequency::NOTE_D4, 200},
        {sound::NoteFrequency::NOTE_C4, 400},
    };
}
