// This file was generated by gen_melodies.py
#pragma once
#include "core/sound.hpp"
namespace melodies {
    constexpr sound::Note joy[] = {
        {sound::NoteFrequency::NOTE_E4, 500},
        {sound::NoteFrequency::NOTE_E4, 500},
        {sound::NoteFrequency::NOTE_F4, 500},
        {sound::NoteFrequency::NOTE_G4, 500},
        {sound::NoteFrequency::NOTE_G4, 500},
        {sound::NoteFrequency::NOTE_F4, 500},
        {sound::NoteFrequency::NOTE_E4, 500},
        {sound::NoteFrequency::NOTE_D4, 500},
        {sound::NoteFrequency::NOTE_C4, 500},
        {sound::NoteFrequency::NOTE_C4, 500},
        {sound::NoteFrequency::NOTE_D4, 500},
        {sound::NoteFrequency::NOTE_E4, 500},
        {sound::NoteFrequency::NOTE_E4, 750},
        {sound::NoteFrequency::NOTE_D4, 250},
        {sound::NoteFrequency::NOTE_D4, 1000},
        {sound::NoteFrequency::NOTE_E4, 500},
        {sound::NoteFrequency::NOTE_E4, 500},
        {sound::NoteFrequency::NOTE_F4, 500},
        {sound::NoteFrequency::NOTE_G4, 500},
        {sound::NoteFrequency::NOTE_G4, 500},
        {sound::NoteFrequency::NOTE_F4, 500},
        {sound::NoteFrequency::NOTE_E4, 500},
        {sound::NoteFrequency::NOTE_D4, 500},
        {sound::NoteFrequency::NOTE_C4, 500},
        {sound::NoteFrequency::NOTE_C4, 500},
        {sound::NoteFrequency::NOTE_D4, 500},
        {sound::NoteFrequency::NOTE_E4, 500},
        {sound::NoteFrequency::NOTE_D4, 750},
        {sound::NoteFrequency::NOTE_C4, 250},
        {sound::NoteFrequency::NOTE_C4, 1000},
    };
}
