// This file was generated by gen_images.py
#pragma once
#include <Arduino.h>
#include <stdint.h>
#include <cstddef>

namespace images {
    constexpr uint8_t alarm_1[] PROGMEM = {
        0b00000000,
        0b00111100,
        0b00100100,
        0b01001010,
        0b01000010,
        0b00100100,
        0b01011010,
        0b00000000,
    };
    constexpr size_t alarm_1_width = 8;
    constexpr size_t alarm_1_height = 8;
}
