// This file was generated by gen_images.py
#pragma once
#include <Arduino.h>
#include <stdint.h>
#include <cstddef>

namespace images {
    constexpr uint8_t battery_0[] PROGMEM = {
        0b00000000,
        0b10011000,
        0b10111100,
        0b10111100,
        0b10111100,
        0b00111100,
        0b10111100,
        0b00000000,
    };
    constexpr size_t battery_0_width = 8;
    constexpr size_t battery_0_height = 8;
}
