// This file was generated by gen_images.py
#pragma once
namespace images {
    constexpr uint8_t battery_0[] = {
        0b00000000,
        0b10011000,
        0b10111100,
        0b10111100,
        0b10111100,
        0b00111100,
        0b10111100,
        0b00000000,
    };
}
