// This file was generated by gen_images.py
#pragma once
#include <Arduino.h>
#include <stdint.h>
#include <cstddef>

namespace images {
    constexpr uint8_t battery_4[] PROGMEM = {
        0b00000000,
        0b00001000,
        0b00010000,
        0b00111100,
        0b00111100,
        0b00001000,
        0b00010000,
        0b00000000,
    };
    constexpr size_t battery_4_width = 8;
    constexpr size_t battery_4_height = 8;
}
