// This file was generated by gen_images.py
#pragma once
namespace images {
    constexpr uint8_t battery_1[] = {
        0b00000000,
        0b00011000,
        0b00111100,
        0b00111100,
        0b00111100,
        0b00100100,
        0b00111100,
        0b00000000,
    };
}
