// This file was generated by gen_images.py
#pragma once
namespace images {
    constexpr uint8_t wifi_1[] = {
        0b00000000,
        0b00000000,
        0b00000000,
        0b00000000,
        0b00000000,
        0b00000000,
        0b00011000,
        0b00000000,
    };
}
