// This file was generated by gen_images.py
#pragma once
namespace images {
    constexpr uint8_t wifi_3[] = {
        0b00000000,
        0b00000000,
        0b01111110,
        0b10000001,
        0b00111100,
        0b01000010,
        0b00011000,
        0b00000000,
    };
}
