// This file was generated by gen_images.py
#pragma once
#include <Arduino.h>
#include <stdint.h>
#include <cstddef>

namespace images {
    constexpr uint8_t wifi_0[] PROGMEM = {
        0b00000001,
        0b00000010,
        0b01111110,
        0b10001001,
        0b00111100,
        0b01100010,
        0b01011000,
        0b10000000,
    };
    constexpr size_t wifi_0_width = 8;
    constexpr size_t wifi_0_height = 8;
}
