// This file was generated by gen_images.py
#pragma once
namespace images {
    constexpr uint8_t wifi_0[] = {
        0b00000001,
        0b00000010,
        0b01111110,
        0b10001001,
        0b00111100,
        0b01100010,
        0b01011000,
        0b10000000,
    };
}
