import pandas as pd
import numpy as np
import glob
import os

music_path = "assets/music/*.csv"
output_base_path = "board/src/melodies/"
os.makedirs(output_base_path, exist_ok=True)

all_music = glob.glob(music_path)
if not all_music:
    raise FileNotFoundError(f"No music files found in {music_path}")

for music_file in all_music:
    music_name = os.path.basename(music_file).split(".")[0]
    
    output_path = os.path.join(output_base_path, f"{music_name}.hpp")
    music_data = pd.read_csv(music_file, names=['note', 'duration'])
    notes = music_data['note'].tolist()
    durations = music_data['duration'].tolist()
    output = \
        "// This file was generated by gen_melodies.py\n" +\
        "#pragma once\n" +\
        "#include \"core/sound.hpp\"\n" +\
        f"namespace melodies {{\n" +\
        f"    constexpr sound::Note {music_name}[] = {{\n"
    for note, duration in zip(notes, durations):
        note_name = note.upper()
        if note_name.endswith('B'):
            note_name[-1] = 'b'
        note_name = f"NOTE_{note_name}"

        output += f"        {{sound::NoteFrequency::{note_name}, {duration}}},\n"
    output += \
        "    };\n" +\
        "}\n"
    
    with open(output_path, "w") as f:
        f.write(output)
    print(f"Generated {output_path}")
