import cv2
import numpy as np
import glob
import os

image_path = "assets/images/*.png"
output_base_path = "board/src/images/"
# Clear and recreate output directory
if os.path.exists(output_base_path):
    for f in glob.glob(os.path.join(output_base_path, "*")):
        os.remove(f)
os.makedirs(output_base_path, exist_ok=True)

total_bits = 0

all_images = glob.glob(image_path)
if not all_images:
    raise FileNotFoundError(f"No images found in {image_path}")

for img in all_images:
    image_name = os.path.basename(img).split(".")[0]
    logo_path = img
    output_path = os.path.join(output_base_path, f"{image_name}.hpp")

    logo_image = cv2.imread(logo_path, cv2.IMREAD_COLOR_RGB)
    assert logo_image is not None, f"Failed to load image {logo_path}"

    output = \
        "// This file was generated by gen_images.py\n" +\
        "#pragma once\n" +\
        "#include <Arduino.h>\n" +\
        "#include <stdint.h>\n" +\
        "#include <cstddef>\n\n" +\
        f"namespace images {{\n" +\
        f"    constexpr uint8_t {image_name}[] PROGMEM = {{\n"
    height, width, _ = logo_image.shape
    # Encode b/w pixels as 1 bit per pixel written as 0bXXXXXXXX
    # White pixel = 1, Black pixel = 0
    for y in range(height):
        row_data = []
        for x in range(0, width, 8):
            byte = 0
            for bit in range(8):
                if x + bit < width:
                    pixel = logo_image[y, x + bit]
                    # Simple threshold to determine black or white
                    if np.mean(pixel) < 128:
                        byte = (byte << 1) | 0
                    else:
                        byte = (byte << 1) | 1
            row_data.append(f"0b{byte:08b}")
        output += "        " + ", ".join(row_data) + ",\n"
    output += "    };\n"
    output += \
        f"    constexpr size_t {image_name}_width = {width};\n" +\
        f"    constexpr size_t {image_name}_height = {height};\n"
    output += "}\n"
    total_bits += width * height + 64 * 2

    with open(output_path, "w") as f:
        f.write(output)
    print(f"Generated {output_path}")

print(f"Total image size: {total_bits//8//1024}KB")